import { Geist, Geist_Mono } from "next/font/google";
import '@fortawesome/fontawesome-free/css/all.min.css';


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import React from 'react'
import Navbar from '@/components/header/header'
import Footer from '@/components/footer/footer'
import { CartProvider } from "./Context/cartContext";

export default function Layout(props) {
  return (
    <>

      <CartProvider>
        <Navbar />
        {props.children}
        <Footer />
      </CartProvider>



    </>
  )
}
